#!/usr/bin/python3

from pyparsing import (alphanums, alphas, nums, CharsNotIn, Combine, Or, Empty,   # NOQA
                       Forward, Group, hexnums, OneOrMore, Literal, Dict, Keyword,
                       Optional, ParseException, ParseSyntaxException, delimitedList,
                       Suppress, Word, ZeroOrMore, quotedString, nestedExpr)


def test(tokens):
    print(tokens)

NUMVAL = Word(nums)
NUMVAR = Word(alphas)
OP = Or(Literal("<") ^ Literal(">") ^
        Literal("<=") ^ Literal(">=") ^
        Literal("=="))
NUMEXPR = Or(Combine(NUMVAR + OP + NUMVAL, adjacent=False) ^
             Combine(NUMVAL + OP + NUMVAR, adjacent=False) ^
             Combine(NUMVAL + OP + NUMVAR + OP + NUMVAL, adjacent=False))
SCOMMA = Suppress(',')
QUOTED_STR = quotedString
NUM = Literal('n') + SCOMMA + NUMEXPR
DATE = Literal('d') + SCOMMA + NUMEXPR + Optional(SCOMMA + QUOTED_STR, default="%Y-%m-%dT%H:%M:%S")
ENUM = Literal('e') + SCOMMA + Word(alphanums)
STR = Literal('s') + SCOMMA + QUOTED_STR
GEN = Empty()
PARAMS = Or(STR ^ ENUM ^ DATE ^ NUM ^ GEN)
OLD = Word(alphanums)
NEW = Word(alphanums)
VAR = OLD + Suppress('=') + NEW + Suppress('[') + Group(PARAMS) + Suppress(']')
parser = delimitedList(VAR)

GEN.setParseAction(lambda tokens: ['g', {}])
NUM.setParseAction(lambda tokens: [tokens[0], dict(expr_pattern=tokens[1])])
DATE.setParseAction(lambda tokens: [tokens[0], dict(expr_pattern=tokens[1],
                                                    date_format=tokens[2])])
ENUM.setParseAction(lambda tokens: [tokens[0], dict(expr_pattern=tokens[1])])
STR.setParseAction(lambda tokens: [tokens[0], dict(expr_pattern=tokens[1])])
QUOTED_STR.setParseAction(lambda tokens: tokens[0][1:-1])
VAR.setParseAction(test)

args = "a=A[e,ahoj], b=B[n, 5<=val<=10], c=C[s, '[,a-z]+'], d=D[], e=E[d, date>2000, '%A %d. %B %Y']"
parser.parseString(args)
