#!/bin/bash

format=DAT
source_file=test.dat

new_str_objects="0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13"
new_str_attrs="note[], outlook[], temperature[], humidity[], windy[], play[]"
classes="Monday, Friday, Friday, Sunday, Theusday, Theusday, Wednesday, Theusday, Monday, Sunday, Suterday, Wednesday, Monday, Sunday"
app="../../../swift-console"

echo $format
echo "====="

# -> csv
$app -s $source_file -t dat.csv -sa "$new_str_attrs"
echo $format "-> CSV"

# -> arff
$app -s $source_file -t dat.arff -sa "$new_str_attrs"
echo $format "-> ARFF"

# -> cxt
$app -s $source_file -t dat.cxt -sa "$new_str_attrs" -to "$new_str_objects"
echo $format "-> CXT"

# -> data
$app -s $source_file -t dat.data -sa "$new_str_attrs" -cls "$classes"
echo $format "-> DATA"
