#!/bin/bash

format=DATA
new_str_attrs="SEX=class[e,woman], WORK=work[e, true], AGE=age[n, 20<x<50], HEIGHT=height[n, y>165], WEIGHT=weight[n, x<90], JOB1=job[e, doctor], JOB2=job[e, student]"
new_str_objects="0, 1, 2, 3"
source_app="cat test.data"
swift="../../../swift-console"
source_format="data"

echo $format
echo "====="

# -> cxt
$source_app | $swift -sf $source_format -tf cxt -ta "$new_str_attrs" -to "$new_str_objects"
echo
echo $format "-> CXT"
echo
echo "#####################################################################################"

# -> csv
$source_app | $swift -sf $source_format -tf csv
echo
echo $format "-> CSV"
echo
echo "#####################################################################################"

# -> arff
$source_app | $swift -sf $source_format -tf arff
echo
echo $format "-> ARFF"
echo
echo "#####################################################################################"

# -> dat
$source_app | $swift -sf $source_format -tf dat -ta "$new_str_attrs"
echo
echo $format "-> DAT"
echo
echo "#####################################################################################"
