#!/bin/bash

source ../../test_config

format=$CSV
new_str_attrs="WINDY=windy:e['TRUE']; SUNNY=outlook:e['sunny']; ORDER=order; TEMP=temperature:n[x>80]; HUM=humidity:n[70<=x<=80]; NOTE=note:s['hell|[0-9]']; BIRTHDAY=birthday:d/'%Y-%m-%d'[date=='2001-04-03']"  
old_str_attrs="note:s; outlook:e; temperature:n; humidity:n; windy:e; play:e; order:e; birthday:d/'%Y-%m-%d'"
source_file=test.csv
source_file_nfl=test_nfl.csv

print_header $format

# -> cxt
$app $source_file_nfl -t csv.cxt -ta "$new_str_attrs_indexes" -o "$new_str_objects" -snh
print_test_info $format $CXT

# -> arff
$app $source_file -t csv.arff -ta "$old_str_attrs" 
print_test_info $format $ARFF

# -> dat
$app $source_file -t csv.dat -ta "$new_str_attrs" 
print_test_info $format $DAT

# -> data
$app $source_file -t csv.data -cls "$classes" -ta "$old_str_attrs"
print_test_info $format $DATA
