#!/bin/bash

format=ARFF
new_str_attrs="WINDY=windy[TRUE]e, SUNNY=outlook[sunny]e, ORDER=order, 
               TEMP=temperature[x>80]n, HUM=humidity[70<=x<=80]n, NOTE=note[hell|[0-9]]s, BIRTHDAY=birthday[date>0:yyyy-MM-dd]d"  
new_str_objects="0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13"
classes="Monday, Friday, Friday, Sunday, Theusday, Theusday, Wednesday, Theusday, Monday, Sunday, Suterday, Wednesday, Monday, Sunday"
source_file=test.arff
app="../../swift.py"

echo $format
echo "====="

# -> cxt
$app -s $source_file -t arff.cxt -ta "$new_str_attrs" -to "$new_str_objects"
echo $format "-> CXT"

# -> csv
$app -s $source_file -t arff.csv
echo $format "-> CSV"

# -> dat
$app -s $source_file -t arff.dat -ta "$new_str_attrs"
echo $format "-> DAT"

# -> data
$app -s $source_file -t arff.data -cls "$classes"
echo $format "-> DATA"
