#!/bin/bash

format=DATA
new_str_attrs="SEX=class[e,woman], WORK=work[e, true], AGE=age[n, 20<x<50], HEIGHT=height[n, y>165], WEIGHT=weight[n, x<90], JOB1=job[e, doctor], JOB2=job[e, student]"
new_str_objects="0, 1, 2, 3"
source_file=test.data
app="../../../swift-console"

echo $format
echo "====="

# -> cxt
$app -s $source_file -t data.cxt -ta "$new_str_attrs" -to "$new_str_objects"
echo $format "-> CXT"

# -> csv
$app -s $source_file -t data.csv
echo $format "-> CSV"

# -> arff
$app -s $source_file -t data.arff
echo $format "-> ARFF"

# -> dat
$app -s $source_file -t data.dat -ta "$new_str_attrs"
echo $format "-> DAT"
