#!/bin/bash

source ../../new_test_config

format=$DATA
new_str_attrs="SEX=class:e['woman']; WORK=work:e['true']; AGE=age:n[20<x<50]; HEIGHT=height:n[y>165]; WEIGHT=weight:n[x<90]; JOB1=job:e['doctor']; JOB2=job:e['student']"
new_str_objects="0, 1, 2, 3"
source_file=test.data

print_header $format

# -> cxt
$app $source_file -t data.cxt -ta "$new_str_attrs" -to "$new_str_objects"
print_test_info $format $CXT

# -> csv
$app $source_file -t data.csv
print_test_info $format $CSV

# -> arff
$app $source_file -t data.arff
print_test_info $format $ARFF

# -> dat
$app $source_file -t data.dat -ta "$new_str_attrs"
print_test_info $format $DAT

# -> data
$app $source_file -t data.data -cls "$classes"
print_test_info $format $DATA
