#!/bin/bash

source ../../test_config

format=$CXT
source_file=test.cxt
source_app="cat test.cxt"
source_format=cxt

print_header $format

# -> csv
$source_app | $app -sf "$source_format" -tf csv
print_test_info $format $CSV

# -> arff
$source_app | $app -sf "$source_format" -tf arff
print_test_info $format $ARFF

# -> dat
$source_app | $app -sf "$source_format" -tf dat
print_test_info $format $DAT

# -> data
$source_app | $app -sf "$source_format" -tf data -cls "$classes"
print_test_info $format $DATA
