#!/bin/bash

format=CXT
source_file=test.cxt
classes="Monday, Friday, Friday, Sunday, Theusday, Theusday, Wednesday, Theusday, Monday, Sunday, Suterday, Wednesday, Monday, Sunday"

echo $format
echo "====="
swift="../../../swift-console"
source_app="cat test.cxt"
source_format=cxt

# -> csv
$source_app | $swift -sf "$source_format" -tf csv
echo
echo $format "-> CSV"
echo
echo "#####################################################################################"

# -> arff
$source_app | $swift -sf "$source_format" -tf arff
echo
echo $format "-> ARFF"
echo
echo "#####################################################################################"

# -> dat
$source_app | $swift -sf "$source_format" -tf dat
echo
echo $format "-> DAT"
echo
echo "#####################################################################################"

# -> data
$source_app | $swift -sf "$source_format" -tf data -cls "$classes"
echo
echo $format "-> DATA"
echo
echo "#####################################################################################"
