#!/bin/bash

source ../../test_config

format=$DAT
new_str_attrs="note=0[], outlook=1[], temperature=2[], humidity=3[], windy=4[], play=5[]"
source_app="cat test.dat"
source_format=dat

print_header $format

# -> csv
$source_app | $app -sf "$source_format" -tf csv -sa "$new_str_attrs"
print_test_info $format $CSV

# -> arff
$source_app | $app -sf "$source_format" -tf arff -sa "$new_str_attrs"
print_test_info $format $ARFF

# -> cxt
$source_app | $app -sf "$source_format" -tf cxt -sa "$new_str_attrs" -to "$new_str_objects"
print_test_info $format $CXT

# -> data
$source_app | $app -sf "$source_format" -tf data -sa "$new_str_attrs" -cls "$classes"
print_test_info $format $DATA
