#!/bin/bash

format=DAT

new_str_objects="0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13"
new_str_attrs="note[], outlook[], temperature[], humidity[], windy[], play[]"
classes="Monday, Friday, Friday, Sunday, Theusday, Theusday, Wednesday, Theusday, Monday, Sunday, Suterday, Wednesday, Monday, Sunday"
swift="../../../swift-console"
source_app="cat test.dat"
source_format=dat

echo $format
echo "====="

# -> csv
$source_app | $swift -sf "$source_format" -tf csv -sa "$new_str_attrs"
echo
echo $format "-> CSV"
echo
echo "#####################################################################################"

# -> arff
$source_app | $swift -sf "$source_format" -tf arff -sa "$new_str_attrs"
echo
echo $format "-> ARFF"
echo
echo "#####################################################################################"

# -> cxt
$source_app | $swift -sf "$source_format" -tf cxt -sa "$new_str_attrs" -to "$new_str_objects"
echo
echo $format "-> CXT"
echo
echo "#####################################################################################"

# -> data
$source_app | $swift -sf "$source_format" -tf data -sa "$new_str_attrs" -cls "$classes"
echo
echo $format "-> DATA"
echo
echo "#####################################################################################"
