#!/bin/bash

format=CXT
source_file=test.cxt
classes="Monday, Friday, Friday, Sunday, Theusday, Theusday, Wednesday, Theusday, Monday, Sunday, Suterday, Wednesday, Monday, Sunday"

echo $format
echo "====="
app=../../fca_swift/swift.py

# -> csv
$app -s $source_file -t cxt.csv
echo $format "-> CSV"

# -> arff
$app -s $source_file -t cxt.arff 
echo $format "-> ARFF"

# -> dat
$app -s $source_file -t cxt.dat 
echo $format "-> DAT"

# -> data
$app -s $source_file -t cxt.data -cls "$classes"
echo $format "-> DATA"
