#!/bin/bash

source ../../test_config

format=$ARFF
none_value="?"
source_app="cat test.arff"
source_format="arff"

print_header $format

# -> cxt
$source_app | $app -sf "$source_format" -tf cxt -sa "$new_str_attrs" -to "$new_str_objects" -nv "$none_value"
print_test_info $format $CXT

# -> csv
$source_app | $app -sf "$source_format" -tf csv -nv "$none_value"
print_test_info $format $CSV

# -> dat
$source_app | $app -sf "$source_format" -tf dat -sa "$new_str_attrs" -nv "$none_value"
print_test_info $format $DAT

# -> data
$source_app | $app -sf "$source_format" -tf data -cls "$classes" -nv "$none_value"
print_test_info $format $DATA
