#!/bin/bash

format=DAT
source_file=test.dat

new_str_objects="0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13"
new_str_attrs="note, outlook, temperature, humidity, windy, play, order"

# -> csv
../../swift.py -s $source_file -t dat.csv -ta "$new_str_attrs"
echo $format "-> CSV"

# -> arff
../../swift.py -s $source_file -t dat.arff -ta "$new_str_attrs"
echo $format "-> ARFF"

# -> cxt
../../swift.py -s $source_file -t dat.cxt -ta "$new_str_attrs" -to "$new_str_objects"
echo $format "-> CXT"
