#!/bin/bash

source ../../test_config

format=$CSV
new_str_attrs="WINDY=windy[e, TRUE], SUNNY=outlook[e, sunny], ORDER=order[], TEMP=temperature[n, x>80], HUM=humidity[n, 70<=x<=80], NOTE=note[s, 'hell|[0-9]'], BIRTHDAY=birthday[d, date=='2001-04-03', '%Y-%m-%d']"  
old_str_attrs="note[s], outlook[e], temperature[n], humidity[n], windy[e], play[e], order[e], birthday[d,'%Y-%m-%d']"
source_file=test.csv
source_app="cat test.csv"
source_format=csv

print_header $format

# -> cxt
cat test_nfl.csv | $app -sf "$source_format" -tf cxt -sa "$new_str_attrs_indexes" -to "$new_str_objects" -nfl
print_test_info $format $CXT

# -> arff
$source_app | $app -sf "$source_format" -tf arff -sa "$old_str_attrs" 
print_test_info $format $ARFF

# -> dat
$source_app | $app -sf "$source_format" -tf dat -sa "$new_str_attrs" 
print_test_info $format $DAT

# -> data
$source_app | $app -sf "$source_format" -tf data -cls "$classes" -sa "$old_str_attrs"
print_test_info $format $DATA
