#!/bin/bash

source ../../test_config

format=$ARFF
none_value="?"
source_file=test.arff

print_header $format

# -> cxt
$app -s $source_file -t arff.cxt -sa "$new_str_attrs" -to "$new_str_objects" -nv "$none_value"
print_test_info $format $CXT

# -> csv
$app -s $source_file -t arff.csv -nv "$none_value"
print_test_info $format $CSV

# -> dat
$app -s $source_file -t arff.dat -sa "$new_str_attrs" -nv "$none_value"
print_test_info $format $DAT

# -> data
$app -s $source_file -t arff.data -cls "$classes" -nv "$none_value"
print_test_info $format $DATA

