#!/bin/bash

format=DATA
new_str_attrs="WINDY=windy[TRUE]e, SUNNY=outlook[sunny]e, ORDER=order, TEMP=temperature[x>80]n, HUM=humidity[70<=x<=80]n, NOTE=note[hell|[0-9]]s"  
new_str_objects="0, 1, 2, 3"
source_file=test.data

echo $format
echo "====="

# -> cxt
# ../../swift.py -s $source_file -t data.cxt -ta "$new_str_attrs" -to "$new_str_objects"
# echo $format "-> CXT"

# -> csv
../../swift.py -s $source_file -t data.csv
echo $format "-> CSV"

# -> arff
../../swift.py -s $source_file -t data.arff
echo $format "-> ARFF"

# -> dat
# ../../swift.py -s $source_file -t data.dat -ta "$new_str_attrs"
# echo $format "-> DAT"
