#!/bin/bash

format=CSV
new_str_attrs="WINDY=windy[TRUE]e, SUNNY=outlook[sunny]e, ORDER=order, 
               TEMP=temperature[x>80]n, HUM=humidity[70<=x<=80]n, NOTE=note[hell|[0-9]]s, BIRTHDAY=birthday[date>0:yyyy-MM-dd]d"  
new_str_objects="0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13"
old_str_attrs="note[s], outlook[e], temperature[n], humidity[n], windy[e], play[e], order[e]"
classes="Monday, Friday, Friday, Sunday, Theusday, Theusday, Wednesday, Theusday, Monday, Sunday, Suterday, Wednesday, Monday, Sunday"
source_file=test.csv
source_file_nfl=test_nfl.csv
app="../../swift.py"

echo $format
echo "====="

# -> cxt
$app -s $source_file_nfl -t csv.cxt -ta "$new_str_attrs" -to "$new_str_objects" -sa "$old_str_attrs" -nfl
echo $format "-> CXT"

# -> arff
$app -s $source_file -t csv.arff -sa "$old_str_attrs" 
echo $format "-> ARFF"

# -> dat
$app -s $source_file -t csv.dat -ta "$new_str_attrs" 
echo $format "-> DAT"

# -> data
$app -s $source_file -t csv.data -cls "$classes" -sa "$old_str_attrs"
echo $format "-> DATA"
